/stereo_merge_node:
  ros__parameters:

    # Fast performance mode
    # Code will run faster, it will be slightly less percise
    fast_performance: True

    yolo_segmentation: True

    # Merge confidence values 
    conf_ss: 20.0 # stereo sonar pointcloud 
    conf_s:  1.0 # sonar-to-image pointcloud 
    conf_e:  0.5 # sonar expansion pointcloud