# Minimum size of area (# of pixels) in the image to be considered contact -> this removes noise
min_area: 1000
boundry: 2 #300
# Invert or not the threshold to look for dark or light areas in the image. Dark = True, Light = False
threshold_inv: False
# Fast performance mode
# Code will run faster, it will be slightly less percise
fast_performance: True

yolo_segmentation: True

# Merge confidence values 
conf_ss: 20.0 # stereo sonar pointcloud 
conf_s:  1.0 # sonar-to-image pointcloud 
conf_e:  0.5 # sonar expansion pointcloud